
# model: BARK
# model_params:
#   warmup_steps: 1000
#   num_samples: 4
#   steps_per_sample: 50
#   num_chains: 4
#   verbose: True

model: Sobo
model_save_name: SoboAlternating
model_params:
  acqf: UCB
  acqf_opt: alternating