benchmark: TreeFunction
benchmark_params:
  dim: 10
  m: 50

num_train: 100
num_test: 1000
model: BARK

model_params:
  warmup_steps: 500
  num_samples: 4
  steps_per_sample: 50
  num_chains: 4
  num_trees: 50
  verbose: True